# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
#    - run: npm run test:staging
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4
      with:
        # key: ${{secrets.AZURE_SSH}}
        host: ${{secrets.AZURE_IP_ADDRESS}}
        username: ${{secrets.AZURE_USERNAME}}
        password: ${{secrets.AZURE_KATALALUAN}}
        script: |
          pm2 delete all
          cd /home/dev/mssql-api
          git pull https://${{secrets.GIT_USERNAME}}:${{secrets.GIT_PAT}}@github.com/farahfuaad/mssql-api.git
          npm install
          pm2 start index.js
